### PR TITLE
Added error reporting to session code

### PR DESCRIPTION
**Pull request by dyeldandi**
We were seeing a number of 
PHP Warning:  Unknown: Failed to write session data (memcached). Please verify that the current setting of session.save_path is correct (foo:11211,bar:11211) in Unknown on line 0
which gave no clue what was going on. This should shed some light on it.

### CODE REVIEW

**Comment by NoodlesNZ** [comment]
Did this help track down these errors? We have had a problem with these types of errors for a couple of years, but haven't been able to track them down.

**Comment by sodabrew** [comment]
There won't be any more released on php-memcached master, can you rebase to php7 branch?

**Comment by sodabrew** [comment]
I've merged the php7 branch to master, so you won't need to change branches, but if you would rebase to current master I can review this for merge!

**Comment by dyeldandi** [comment]
Created pull request #301

**Pull request closed without merging**
