### PR TITLE
PHP7 Support

### PR DESCRIPTION
**Pull request by rlerdorf**
This should bring the extension up to speed with current PHP7. Some of these changes are pulled from the previous phpng PR from @zxcvdavid but most of it is new. It compiles but hasn't been heavily tested.

I didn't ifdef due to the number of changes, so I suggest a separate php7 branch.

### CODE REVIEW

**Comment by mkoppanen** [comment]
Would it make sense for us to create a php7 branch and then have this PR reopened against that branch?

**Comment by rlerdorf** [comment]
Yeah, I think that would be cleanest approach. A bit crappy that we will need to remember to commit changes to both branches, but trying to ifdef everything would get messy. The php7-only code is quite a bit cleaner now too I think.

**Comment by mkoppanen** [comment]
Added the new branch: https://github.com/php-memcached-dev/php-memcached/tree/php7

Can you reopen the pull against the branch?

**Comment by krakjoe** [comment]
This was done in another branch, so closing ... please do join in the php7 branch though ..

**Pull request closed without merging**
