### PR TITLE
Add testcase for get-method overload

### LINKED ISSUE #126: User-flags related changes cause issues during inheritance
More information:

symfony/symfony#9797

https://bugs.php.net/bug.php?id=66331

### PR DESCRIPTION
**Pull request by SjonHortensius**
Test change introduce in #209 to fix #126

### CODE REVIEW

**Comment by sodabrew** [comment]
This presently fails with:
```
Warning: Declaration of test_overload_get::get($key, $cache_cb = NULL, &$cas_token = NULL) should be compatible with Memcached::get($key, $cache_cb = NULL, $get_flags = NULL) in tests/overload_get.php
```

**Comment by SjonHortensius** [comment]
I originally added this test to make sure php7 userland code will be able to overload `Memcached::get` successfully. After adding this test, dc5b22a8da fixed the issue, but broke this test.

I've added a commit that fixes the test by implementing the new `get()` signature

**Comment by sodabrew** [comment]
Thanks for your responsiveness @SjonHortensius! I'm going to close this PR without merging, however. The test at this point is no longer checking the underlying (and unresolved) PHP 
https://bugs.php.net/bug.php?id=66331 and so the effect is just to test normal class inheritance, which is basic PHP and not something we need tests for here.

The php-memcached API going forward adds a flag field to `get` and `getMulti`, with the value `Memcached::GET_EXTENDED` changing the methods to return an array. Because the flags field is a pass-by-value integer, it's possible to subclass or override the method using the normal PHP syntax without running into the corner case with the references.

**Comment by SjonHortensius** [comment]
@sodabrew thanks for explaining. I agree with your statement, and I hope php-memcached will only implement signatures in the future which can be overloaded normally.

**Pull request closed without merging**
