### PR TITLE
Added memcached.sess_prefix for --SERVER= connection string

### PR DESCRIPTION
**Pull request by dyeldandi**
A quick fix for issue #281

### CODE REVIEW

**Comment by sodabrew** [comment]
It looks like this fix only applies the prefix if `--SERVERS` is _not_ used. It looks like both cases need to be handled (or refactored so that the same code adds prefixes regardless of how the servers array was specified).

**Comment by dyeldandi** [comment]
> It looks like this fix only applies the prefix if --SERVERS is not used.
Not exactly. It jumps to that "else" branch on "goto success;" It's kind of ugly, but it was there initially and I tried to do the minimal changes keeping the logic as it is.

**Comment by sodabrew** [comment]
Could I ask you to rebase your branch against master? There are some merge conflicts right now.

**Comment by dyeldandi** [comment]
You don't need to merge this to master, it looks like in php7 branch this part has been completely rewritten.

**Comment by sodabrew** [comment]
Im probably not going to make another 2.x release, but if you wanted this fix for 2.2.1, adjust the PR base branch to REL2_0

**Comment by dyeldandi** [comment]
Yes, that would be very nice. Created pull #304. Thanks a lot!

**Pull request closed without merging**
