### PR TITLE
promote error "Memcached constructor was not called" to exception

### PR DESCRIPTION
**Pull request by remicollet**
For consistency with other PHP 8 extensions.

### CODE REVIEW

**Comment by sodabrew** [comment]
This seems fine. I'm not sure I understand why this would be PHP 8 only though, would it be reasonable to change across the board?

**Comment by remicollet** [comment]
> I'm not sure I understand why this would be PHP 8 

This change is a behavior change, which is usually not expected in stable releases.

Having error promoted to exception is a common behavior for all extensions from php-src (TypeError during zend_parse_parameters, ValueError, ...)

**Comment by sodabrew** [comment]
I would do the next release as 3.2.0, so I'm comfortable making this change a release note. The part I'm missing here is whether `zend_throw_error` and `RETURN_THROW` are available in PHP 7.x as well?

**Comment by remicollet** [comment]
> The part I'm missing here is whether zend_throw_error 

Yes

> and RETURN_THROW are available in PHP 7.x as well?

No (but this is a simple "return")

On PHP 8 **zend_parse_parameter** also throw eception by default (exception is ZEND_PARSE_PARAMS_QUIET is used)

So for consistency, if you want to raise exceptions, and want to keep PHP 7 / 8 behavior the same, you also have to switch from 

`ZEND_PARSE_PARAMETERS_START(...`

to 

`ZEND_PARSE_PARAMETERS_START_EX(ZEND_PARSE_PARAMS_THROW...`

**Pull request merged**
