### PR TITLE
Php7

### PR DESCRIPTION
**Pull request by nickzhuyb**

### CODE REVIEW

**Comment by sodabrew** [comment]
What is the purpose of this pull request?

**Comment by jrchamp** [comment]
Probably an accident. I see this happen a lot on openssl. Should probably just close it.

**Comment by NoodlesNZ** [comment]
Maybe someone hopeful that we'll get php7 support in the master branch and maybe a release soon?

**Comment by sebastien-fauvel** [comment]
If looks like @oerdnj has released a php7 extension for memcached in the Ubuntu repository [ppa:ondrej/php](https://launchpad.net/~ondrej/+archive/ubuntu/php/+index) on May 24th (my birthday!). Does anyone happen to know which commit has being used for this (unofficial) release? Who is taking care of releasing it on PECL? I would really appreciate it!

**Pull request closed without merging**
