### PR TITLE
Separate test for 64-bit increment/decrement/incrementByKey/decrementByKey

### PR DESCRIPTION
**Pull request by sodabrew**
#320 beat me to it :)

### CODE REVIEW

**Comment by remicollet** [comment]
The die message MUST start with "skip, else the test if never skipped"...

```
TEST 37/82 [tests/incrdecr_64.phpt]
========DIFF========
004+ 
005+ Warning: Memcached::increment() expects parameter 2 to be integer, float given in /builddir/build/BUILD/php-pecl-memcached-3.0.1/ZTS/tests/incrdecr_64.php on line 10
006+ int(1)
007+ 
008+ Warning: Memcached::decrement() expects parameter 2 to be integer, float given in /builddir/build/BUILD/php-pecl-memcached-3.0.1/ZTS/tests/incrdecr_64.php on line 13
004- int(4294967297)
007- int(4294967297)
011+ 
012+ Warning: Memcached::incrementByKey() expects parameter 3 to be integer, float given in /builddir/build/BUILD/php-pecl-memcached-3.0.1/ZTS/tests/incrdecr_64.php on line 17
013+ int(1)
014+ 
015+ Warning: Memcached::decrementByKey() expects parameter 3 to be integer, float given in /builddir/build/BUILD/php-pecl-memcached-3.0.1/ZTS/tests/incrdecr_64.php on line 20
========DONE========
FAIL 64-bit Memcached::increment() decrement() incrementByKey() decrementByKey() [tests/incrdecr_64.phpt] 

```

**Comment by sodabrew** [comment]
Updated.

**Comment by remicollet** [comment]
Tested on :
* RHEL-7, x86_64, PHP 7.1
* RHEL-6, i686, PHP 7.0

LGTM 
even if when you have 64, bit probably need a "s" ;)

**Comment by sodabrew** [comment]
I think 64-bit vs. 64-bits might depend on which side of the Atlantic one computes on! :)

**Pull request merged**
