### PR TITLE
use false as default value for boolean

### PR DESCRIPTION
**Pull request by remicollet**
as null is not really allowed

### CODE REVIEW

**Comment by sodabrew** [comment]
I had suspected as much but hadn't run it down.

**Comment by m6w6** [comment]
Oops, sorry, just noticed #472 accidentally includes this, too...

**Comment by remicollet** [comment]
> Oops, sorry, just noticed #472 accidentally includes this, too...

no problem

**Comment by sodabrew** [comment]
Merged with #472

**Pull request closed without merging**
