### PR TITLE
fix MemcachedServer

### PR DESCRIPTION
**Pull request by m6w6**
related: #418, #473, m6w6/libmemcached#94

### CODE REVIEW

**Comment by remicollet** [comment]
Tried, and works as expected (using `server-example` scripts)

So +1

**Comment by remicollet** [comment]
@m6w6 here is a backtracen seems related to flush call

```
(gdb) bt
#0  s_flush_handler (when=<optimized out>, cookie=<optimized out>) at /work/GIT/pecl-and-ext/memcached/php_memcached_server.c:304
#1  s_flush_handler (cookie=<optimized out>, when=<optimized out>) at /work/GIT/pecl-and-ext/memcached/php_memcached_server.c:291
#2  0x00007ffff7f95b20 in flush_command_handler () from /lib64/libmemcachedprotocol.so.0
#3  0x00007ffff7f96bdc in memcached_binary_protocol_process_data () from /lib64/libmemcachedprotocol.so.0
#4  0x00007ffff7f97a0e in memcached_protocol_client_work () from /lib64/libmemcachedprotocol.so.0
#5  0x00007ffff754be18 in s_handle_memcached_event (fd=7, what=<optimized out>, arg=0x7ffff726c120) at /work/GIT/pecl-and-ext/memcached/php_memcached_server.c:626
#6  0x00007ffff746c774 in event_once_cb () from /lib64/libevent-2.1.so.6
#7  0x00007ffff7471b54 in event_process_active_single_queue () from /lib64/libevent-2.1.so.6
#8  0x00007ffff74735d7 in event_base_loop () from /lib64/libevent-2.1.so.6
#9  0x00007ffff754df56 in php_memc_proto_handler_run (handler=0x7ffff7257a00, address=0x7ffff7294cf8) at /work/GIT/pecl-and-ext/memcached/php_memcached_server.c:793
#10 0x00007ffff75416d0 in zim_MemcachedServer_run (execute_data=<optimized out>, return_value=0x7fffffff9bd0) at /work/GIT/pecl-and-ext/memcached/php_memcached.c:3838
#11 0x000055555585691d in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.4.14-1.fc33.remi.x86_64/Zend/zend_vm_execute.h:1618
#12 execute_ex (ex=0x7ffff729be18) at /usr/src/debug/php-7.4.14-1.fc33.remi.x86_64/Zend/zend_vm_execute.h:53861
#13 0x0000555555858c7b in zend_execute (op_array=0x7ffff72892a0, return_value=0x0) at /usr/src/debug/php-7.4.14-1.fc33.remi.x86_64/Zend/zend_vm_execute.h:57957
#14 0x00005555557cf49c in zend_execute_scripts (type=type@entry=8, retval=0x7ffff72a5960, retval@entry=0x0, file_count=-148819936, file_count@entry=3)
    at /usr/src/debug/php-7.4.14-1.fc33.remi.x86_64/Zend/zend.c:1679
#15 0x000055555576c730 in php_execute_script (primary_file=<optimized out>) at /usr/src/debug/php-7.4.14-1.fc33.remi.x86_64/main/main.c:2621
#16 0x000055555585ad7a in do_cli (argc=11, argv=0x555555e21150) at /usr/src/debug/php-7.4.14-1.fc33.remi.x86_64/sapi/cli/php_cli.c:964
#17 0x000055555563c42e in main (argc=11, argv=0x555555e21150) at /usr/src/debug/php-7.4.14-1.fc33.remi.x86_64/sapi/cli/php_cli.c:1359

```

**Comment by remicollet** [comment]
Seems to do the work
```
@@ -296,6 +299,7 @@ protocol_binary_response_status s_flush_handler(const void *cookie, uint32_t whe
        }
 
        MEMC_MAKE_ZVAL_COOKIE(zcookie, cookie);
+       ZVAL_LONG(&zwhen, when);
 
        ZVAL_COPY(&params[0], &zcookie);
        ZVAL_COPY(&params[1], &zwhen);

```

**Comment by sodabrew** [comment]
This looks really good! Please let me know when you're confident with this PR and I'll land it.

**Comment by m6w6** [comment]
Thanks Remi!

This was quite a rabbit hole. The actual bug is/was in libmemcachedprotocol, see https://github.com/m6w6/libmemcached/commit/2a67d9900d37f4ec3164294fcf95e0efb8a49a64

**Comment by remicollet** [comment]
Was also searching a way to send the "END" message...

BTW shouln't we use in server.php
As discussed on IRC, for memory

```
$server->on (Memcached::ON_STAT,
             function ($client_id, $key, &$value) {
                 echo "client_id=[$client_id]: Stat key=[$key]" . PHP_EOL;
				if ($key) {
	                 $value = "Stat reply for $key";
				} else {
	                 $value = ['foo' = > 'Stat Reply', 'bar' => 'Another'];
				}
                 return Memcached::RESPONSE_SUCCESS;
             });
```

**Comment by m6w6** [comment]
I'd prefer to always expect an array

**Comment by m6w6** [comment]
I think this should be fine now, or do you have anything to add @remicollet ?

**Comment by remicollet** [comment]
+1  LGTM

**Comment by remicollet** [comment]
@m6w6 can you please rebase ?

**Pull request merged**
