### PR TITLE
Add GitHub Actions build

### PR DESCRIPTION
**Pull request by mszabo-wikia**
travis-ci.org builds have ceased, so this patch adds a GitHub Actions
workflow to build and test the extension, as well as a Dependabot
configuration file to keep the referenced actions up to date.

I've opted to slightly simplify the workflow compared to the Travis
build script. For one, I have not included libmemcached protocol
support, as most distros do not supply a libmemcached compiled with
server protocol support, and previous discussion suggests its usefulness
in the context of this extension may be limited.[1] I've also opted to
remove multiversion libmemcached testing in favor of using the system
libmemcached, as the referenced other versions seem to be old enough for
this to hopefully not be a problem. These could conceivably be
reintroduced if needed.

---
[1] https://github.com/php-memcached-dev/php-memcached/issues/418#issuecomment-449587972

### CODE REVIEW

**Comment by ruudk** [comment]
@remicollet Can this be merged? When this is merged I'd like to add tests for PHP 8.1 so that we can work towards supporting that.

**Comment by sodabrew** [comment]
@mszabo-wikia This is awesome! @ruudk thanks for the ping on this PR, I had missed it, and I even have a whole bunch of tabs bookmarked for the past few months with tutorials on how to switch from Travis to GitHub Actions :)

Merging as-is. We can iterate later. Thank you!

**Comment by mszabo-wikia** [comment]
Great, thank you! :)

**Comment by ruudk** [comment]
Thanks for merging. I see that this PR already added PHP 8.1 support as experimental. Given that the tests pass, maybe it shouldn't be experimental anymore?

**Pull request merged**
