### PR TITLE
Move working tests out of the experimental folder

### PR DESCRIPTION
**Pull request by xPaw**
This should do the trick.

### CODE REVIEW

**Comment by xPaw** [comment]
I tried to fix up some of the tests, but some of them are broken beyond my comprehension. Some tests have differences based on PHP version.

**Comment by xPaw** [comment]
I've moved working tests out of the experimental folder, so there's more passing tests on the CI now.

There's less than 10 tests left in experimental folder, unfortunately I'm not entirely sure how to fix them (and some of them start failing on newer php versions).

**Comment by xPaw** [comment]
@remicollet is there any interest in merging this?

**Comment by sodabrew** [comment]
Thanks for doing this! Helpful to isolate the few non-working tests for future improvement.

**Pull request merged**
