### PR TITLE
Fixes memory errors, broken code, bugs etc

### PR DESCRIPTION
**Pull request by mkoppanen**

### CODE REVIEW

**Comment by mkoppanen** [comment]
Fixes #199 among other issues.

**Comment by xjewer** [comment]
@mkoppanen I have some trouble with cas_token, seems it isn’t processed https://github.com/mkoppanen/php-memcached/blob/a930b41fa138a55b976c55e21157e57b09355343/php_memcached.c#L1356

**Comment by xjewer** [comment]
ohh, i see, cas is passed through the context, hovewer it doesn’t work

**Comment by mkoppanen** [comment]
@xjewer, cas parameters has been removed (signature change). It was causing issues with inheritance.

**Comment by xjewer** [comment]
:see_no_evil:  i found out  `cas` work only for delayed request now, should to note about it

**Comment by mkoppanen** [comment]
package.xml has release notes that contain the note

**Comment by xjewer** [comment]
:ok_hand:

**Comment by fadimko** [comment]
@mkoppanen So a user can set `Memcached::GET_EXTENDED`, so cas_token and user flags will be retrieved inside of a `get()` call, but the user can't get them?
> * set/get commands do not take cas or user flags parameters.
> * get and getMulti commands take Memcached::GET_EXTENDED flag to retrieve user flags and cas tokens

**Comment by mkoppanen** [comment]
@fadimko there is a cas and casMulti for CAS operations

**Comment by fadimko** [comment]
How can I retrieve them after a `get()` call?

**Comment by mkoppanen** [comment]
@fadimko, after a get call? You would retrieve them with Memcached::GET_EXTENDED during a get call

**Comment by fadimko** [comment]
@mkoppanen Oh, now I see. I didn't noticed this string:
>context.return_value = return_value;

https://github.com/php-memcached-dev/php-memcached/blob/php7/php_memcached.c#L1405

**Comment by fadimko** [comment]
Thank you

**Comment by mkoppanen** [comment]
@fadimko, yep. It's not ideal from API perspective but it fixes issues with inheriting the class and overriding get (for example PHPUnit seems to do this)

**Comment by xjewer** [comment]
what about difference between signature and arginfo? 
`ZEND_ARG_INFO(0, get_flags)` has been missed or omitted?

https://github.com/php-memcached-dev/php-memcached/blob/php7/php_memcached.c#L1394
https://github.com/php-memcached-dev/php-memcached/blob/php7/php_memcached.c#L3719

```C
if (zend_parse_parameters(ZEND_NUM_ARGS(), "S|f!l", &key, &fci, &fcc, &get_flags) == FAILURE) {
	return;
}
```

```C
ZEND_BEGIN_ARG_INFO_EX(arginfo_get, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, cache_cb)
ZEND_END_ARG_INFO()
```

**Comment by mkoppanen** [comment]
I think missed. Can you open a pr for that?

**Comment by xjewer** [comment]
>I think missed. Can you open a pr for that?

#223

**Comment by letynsoft** [comment]
And what about AT LEAST mentioning it on the PHP manual page? One year later and this is not mentioned anywhere! http://php.net/manual/en/memcached.get.php

**Comment by sodabrew** [comment]
@letynsoft Editing the manual is a whole separate workflow. Community contributions highly appreciated on this.

**Pull request merged**
