### PR TITLE
Create gh_500.phpt

### PR DESCRIPTION
**Pull request by xPaw**
Quick test for #500

### CODE REVIEW

**Comment by sodabrew** [comment]
Thanks for creating a test for this!  Just approved the GitHub actions run.

**Comment by sodabrew** [comment]
Tests passing, please let me know if you plan to add anything more to this PR? If not I'll merge it!

**Comment by xPaw** [comment]
Hmm if they pass, wonder what's up with that then. Is the sury package I am using missing a fix it something

**Comment by remicollet** [comment]
Squashed and merged

**Pull request closed without merging**
